### ISSUE TITLE
Explore options for adding a GraphQL endpoint as a spring module

### ISSUE THREAD

**Issue by outten45** [vivo-community/vivo-graphql#10]
Understand the options available for providing GraphQL from a spring boot app.

* [x] report back to the backend implementation team 

**Stretch**

* Add a graphql to the [TAMU/Scholars](https://github.com/TAMULib/Scholars) repo and model out some data

**Comment by jimwood** [comment]
Was able to add a graphql endpoint and reuse the existing models and repositories.

Added a sample people query allowing for basic search and pagination

Added document resolver to person so related documents can be fetched along with person data
