### ISSUE TITLE
Create docker-compose to run TAMU/Scholars locally

### ISSUE THREAD

**Issue by outten45** [vivo-community/vivo-graphql#8]
The goal would be to create a docker environment for running, developing and exploring the [TAMULib/Scholars](https://github.com/TAMULib/Scholars) instance. 

* [x] Create a docker-compose.yml for running the TAMU/Scholars application in local development.
* [x] This should start a SOLR and middleware instance
* [x] Document how to install

**Stretch Goal**
* Get angular front-end included in the docker-compose.yml

**Testing**

@awoods offered to give it a try once we have it working.

**Comment by chemGoggles** [comment]
It would be good to clarify which individuals need to have this running locally (with sample data) and by when.
